name: Build WASM

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # 删除了 cache: 'npm' 以避免报错

      # 安装 Emscripten SDK
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.64
          actions-cache-folder: 'emsdk-cache'

      - name: Install Dependencies
        run: npm install

      # 编译 WASM
      - name: Build WASM
        run: npx tree-sitter build --wasm

      # 上传产物
      - name: Upload WASM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-dart-wasm
          path: tree-sitter-dart.wasm
          retention-days: 5
